---
- hosts: all
  connection: local
  gather_facts: true
  name: Example Policy Lookup Playbook

  vars:
    provider:
      ip_address: "{{ panorama_ip_address }}"
      username: "{{ username | default(lookup('env', 'ANSIBLE_NET_USERNAME')) }}"
      password: "{{ password | default(lookup('env', 'ANSIBLE_NET_PASSWORD')) }}"
      serial_number: "{{ serialno }}"
    exit_on_fail: true

  roles:
    - run_readiness_checks