---
argument_specs:
  main:
    short_description: Runs pre-upgrade test suite and takes an operational snapshot.
    description:
      - >-
        Runs the pre-upgrade ('readiness') tests and takes a snapshot of the operational state of the target 
        firewall.
    options:
      panorama_ip_address:
        type: "str"
        required: true
        description: "The PANORAMA IP address to calls through"
      serialno:
        type: "str"
        required: true
        description: "The serial number of the firewall to run checks on"
      username:
        type: "str"
        required: false
        description: "Firewall login username - defaults to envvar ANSIBLE_NET_USERNAME"
      password:
        type: "str"
        required: false
        description: "Firewall login password - defaults to ennvar ANSIBLE_NET_PASSWORD"
      version:
        type: "str"
        required: true
        description: "Software version to install"