---
argument_specs:
  main:
    short_description: Runs pre-upgrade test suite and takes an operational snapshot.
    description:
      - >-
        Runs the pre-upgrade ('readiness') tests and takes a snapshot of the operational state of the target 
        firewall.
    options:
      left_snapshot:
        type: "str"
        required: true
        description: "The first snapshot to compare, usually this snapshot is the one taken before any upgrades"
      right_snapshot:
        type: "str"
        required: true
        description: "The second snapshot to compare, usually this snapshot is the one taken after any upgrades or changes"