---
snapshot_directory: "./snapshots"
snapshot_filename: "snapshot_{{ ansible_date_time.epoch }}_{{ provider.serial_number }}"
snapshot_output_file: "{{ [ snapshot_directory, snapshot_filename] | path_join }}.json"