---
name: Make and Release Execution Environment Image

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: 3.11

      - name: Install Ansible Builder
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder

      - name: Build docker context
        run: |
          ansible-builder create -f meta/execution-environment.yml --output-filename Dockerfile

      - name: login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List directories
        run: |
          ls -l ./context

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and publish
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: "./context/"
          file: "./context/Dockerfile"
          push: true
          tags: ghcr.io/paloaltonetworks/ansible-panos-upgrade-example:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: ${{ inputs.release }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@1c8dbaa298552ad40802cf44320879943de90278 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
