---
- name: Debug - Print what we're doing
  ansible.builtin.debug:
    msg: |
      Failover of device {{ provider.serialno }} to state {{ state }}. !! this is may cause traffic interruption !!
      
- name: Suspend local HA node
  paloaltonetworks.panos.panos_op:
    provider: '{{ provider }}'
    cmd: 'request high-availability state {{ state }}'